//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInCourse
    {
        public int ID { get; set; }
        public Nullable<int> CoursesID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CurrentLesson { get; set; }
        public Nullable<int> points { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
